version: 0.2

batch:
  fast-fail: true
  build-graph:
    - identifier: linux_small
      env:
        compute-type: BUILD_GENERAL1_SMALL
      ignore-failure: true  
    - identifier: linux_medium
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
      ignore-failure: true
      depend-on:
        - linux_small
    - identifier: linux_large
      env:
        compute-type: BUILD_GENERAL1_LARGE
      depend-on:
        - linux_medium
      ignore-failure: true

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo 'Compiling the Java Code'
      - javac -cp . HelloWorld.java
      - if [ $CODEBUILD_BUILD_NUMBER -gt 5 ]; then fail; fi
  post_build:
    commands:
      - echo "Would deploy here"
artifacts:
  files:
    - 'HelloWorld.class'
